services:
  localito-pos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: localito-reisbloc-fnb
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_SUPABASE_URL=https://htjhzdtlvdbtlfdhsydq.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0amh6ZHRsdmRidGxmZGhzeWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MDQ0MTAsImV4cCI6MjA4NzQ4MDQxMH0.j5v9FHF-MzFzxWU06aMBMMP6KB6ywkphdlMz3pPdJhw
      - VITE_EVENT_ORGANIZATION_ID=1a70643e-23a3-4224-939e-d7daf381c083
      - VITE_CLIENT_NAME=LOCALITO
      - VITE_CLIENT_SUBDOMAIN=localito.reisbloc.com
